There is more than one default config file

diff --git a/bin/uzbl-browser.in b/bin/uzbl-browser.in
--- a/bin/uzbl-browser.in
+++ b/bin/uzbl-browser.in
@@ -38,7 +38,7 @@ if [ ! -f "$XDG_CONFIG_HOME/uzbl/config" ]; then
 	[ -r "$EXAMPLES/config/config" ] || \
 		die_with_status 3 "Error: Global config not found; please check if your distribution ships them separately"
 	if ! cp "$EXAMPLES/config/"* "$XDG_CONFIG_HOME/uzbl/"; then
-		echo >&2 "Could not copy default config to $XDG_CONFIG_HOME/uzbl/config"
+		echo >&2 "Could not copy default configs to $XDG_CONFIG_HOME/uzbl"
 		# Run with the global config as a last resort
 		config_file="$EXAMPLES/config/config"
 	fi
