Use the global configuration as a fallback
First check if there isn't a global config. If there isn't *then* we can
fail. If there is and the copy fails, at least run with the global
configuration.

diff --git a/src/uzbl-browser b/src/uzbl-browser
--- a/src/uzbl-browser
+++ b/src/uzbl-browser
@@ -40,10 +40,16 @@ done
 # if no config exists yet in the recommended location, put the default (recommended) config there
 if [ ! -f $XDG_CONFIG_HOME/uzbl/config ]
 then
+	if [ ! -r $PREFIX/share/uzbl/examples/config/config ]
+	then
+		echo "Error: Global config not found; please check if your distribution ships them separately"
+		exit 3
+	fi
 	if ! cp $PREFIX/share/uzbl/examples/config/config $XDG_CONFIG_HOME/uzbl/config
 	then
 		echo "Could not copy default config to $XDG_CONFIG_HOME/uzbl/config" >&2
-		exit 3
+		# Run with the global configs as a last resort
+		config="--config $PREFIX/share/uzbl/examples/config/config"
 	fi
 fi
 
@@ -63,4 +69,4 @@ DAEMON_PID=${DAEMON_SOCKET}.pid
 	uzbl-event-manager -va start
 #fi
 
-exec uzbl-core "$@" --connect-socket $DAEMON_SOCKET
+exec uzbl-core "$@" $config --connect-socket $DAEMON_SOCKET
